# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-04-09 05:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('ProjectID', models.IntegerField(primary_key=True, serialize=False)),
                ('ProjectName', models.CharField(blank=True, max_length=25, null=True)),
                ('ClientID', models.IntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, max_length=25, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('TaskID', models.IntegerField(primary_key=True, serialize=False)),
                ('TaskName', models.CharField(blank=True, max_length=25, null=True)),
                ('TaskSecID', models.IntegerField()),
                ('AssignedTo', models.IntegerField(blank=True, null=True)),
                ('Notes', models.TextField(blank=True, max_length=1000)),
                ('ProjectRef', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='projectID', to='productdetails.Project')),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='RefProjectType',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ProjecttypeID', to='productdetails.ProjectType'),
        ),
    ]
