# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-11-12 08:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalInventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=20, unique=True)),
                ('description', models.TextField(max_length=20, null=True)),
                ('price', models.IntegerField()),
                ('image', models.ImageField(upload_to='')),
            ],
            options={
                'db_table': 'GlobalInventory',
            },
        ),
    ]
