# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-11-12 08:23
from __future__ import unicode_literals

from django.db import migrations, models
import inventory.models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='globalinventory',
            name='description',
            field=models.TextField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='globalinventory',
            name='image',
            field=models.ImageField(blank=True, max_length=254, null=True, upload_to=inventory.models.nameFile),
        ),
    ]
